@startuml
1 -> 0: FIND_NODE[00000001]
0 -> 1: FIND_NODE_RESPONSE[00000001]
2 -> 0: FIND_NODE[00000002]
0 -> 2: FIND_NODE_RESPONSE[00000002]
3 -> 0: FIND_NODE[00000003]
0 -> 3: FIND_NODE_RESPONSE[00000003]
4 -> 0: FIND_NODE[00000004]
0 -> 4: FIND_NODE_RESPONSE[00000004]
5 -> 0: FIND_NODE[00000005]
0 -> 5: FIND_NODE_RESPONSE[00000005]
6 -> 0: FIND_NODE[00000006]
0 -> 6: FIND_NODE_RESPONSE[00000006]
7 -> 0: FIND_NODE[00000007]
0 -> 7: FIND_NODE_RESPONSE[00000007]
8 -> 0: FIND_NODE[00000008]
0 -> 8: FIND_NODE_RESPONSE[00000008]
9 -> 0: FIND_NODE[00000009]
0 -> 9: FIND_NODE_RESPONSE[00000009]
0 -> 4: PING_NODE[0000000a]
4 -> 0: PING_NODE_RESPONSE[0000000a]
None -> 0: TERMINATE_NODE[0000000b]
None -> 1: TERMINATE_NODE[0000000c]
None -> 2: TERMINATE_NODE[0000000d]
None -> 3: TERMINATE_NODE[0000000e]
None -> 4: TERMINATE_NODE[0000000f]
None -> 5: TERMINATE_NODE[00000010]
None -> 6: TERMINATE_NODE[00000011]
None -> 7: TERMINATE_NODE[00000012]
None -> 8: TERMINATE_NODE[00000013]
None -> 9: TERMINATE_NODE[00000014]
@endtuml
# "C:\Program Files (x86)\Common Files\Oracle\Java\javapath"\java.exe -jar "C:\Users\Denis BEURIVE\Documents\software"\plantuml.jar <file>
